### ISSUE TITLE
  the npmjs.org doc index isn't hyper-linked 

### ISSUE THREAD

**Issue by frankcash** [npm/docs.npmjs.com#102]
https://docs.npmjs.com/misc/index

would be beneficial if this page was hyper-linked to corresponding documentation page

ref: https://github.com/npm/npm/issues/7065

**Comment by smikes** [comment]
Oh man has this been an epic runaround!  See also <https://github.com/npm/newww/issues/494> which was created as a follow-on from <https://github.com/npm/npm/issues/7065>.

It looks to me like the `/misc/index` page is generated by `bin/tree.js` from `npm/doc/misc/npm-index.md` 

Relevant code is right around here...
https://github.com/npm/docs.npmjs.com/blob/ea51f469fda3612ef0c8efe091b130f79f1b161e/bin/tree.js 

The "obvious" approach would be to special-case the handling of `npm-index.md` but that's probably a terrible idea.  (If it's not a terrible idea, let me know and I will write a PR that does that.)

**Comment by zeke** [comment]
@smikes your assumptions are all correct here. I think we should just get rid of this page entirely and add a redirect to `/`, or perhaps https://docs.npmjs.com/all

Patches welcome!

**Comment by zeke** [comment]
https://docs.npmjs.com/misc/index now redirects to https://docs.npmjs.com/

Thanks for playing!

**Comment by smikes** [comment]
Will PR #103 be merged soon or has it been superceded?
