### ISSUE TITLE
convert 'see also' items into hyperlinks

### ISSUE THREAD

**Issue by zeke** [npm/docs.npmjs.com#105]
https://docs.npmjs.com/misc/scripts#see-also

![screen shot 2015-01-07 at 10 53 33 am](https://cloud.githubusercontent.com/assets/2289/5651343/7bf091f2-965b-11e4-96f1-ad27edb65074.png)

**Comment by zeke** [comment]
Closing because this new dupe adds more detail: https://github.com/npm/docs.npmjs.com/issues/105

**Comment by jcrben** [comment]
@zeke - are you sure you didn't mean to refer to a different issue than #105 (which is this issue).
