### ISSUE TITLE
Markdown does not properly escape '<' and '>'

### ISSUE THREAD

**Issue by philosoralphter** [npm/docs.npmjs.com#112]
It works on github markdown if I use escaped greater than or less than signs (for instance to denote type for function argument.) 

 eg: function doSomething( numTimes:<int>, toWhom:<string> )

This style of notation does not work at all because there is no way to escape the  < > characters.  They are read as html tags.

**Comment by linclark** [comment]
I'm guessing that this issue is about the package page: https://www.npmjs.com/package/rate_limiter

If so, the code for that site is in a different repository. You should post to https://github.com/npm/newww

**Comment by zeke** [comment]
@philosoralphter wins the awesome github handle award.

**Comment by philosoralphter** [comment]
ok thanks @linclark.  ha ha and thank you, @zeke
