### ISSUE TITLE
Punctuation in code blocks appearing as html-entity-like objects

### ISSUE THREAD

**Issue by olizilla** [npm/docs.npmjs.com#117]
The markdown source for these files has literals, but something is over-zealously encoding them to html entities then the code highlighter is dicing them up so it can render them as code.

![screenshot 2015-02-06 15 45 11](https://cloud.githubusercontent.com/assets/58871/6082192/2d69f5d6-ae17-11e4-8a03-990f1673702a.png)

**Comment by zeke** [comment]
oops. thanks for reporting.

**Comment by zeke** [comment]
```
  _____ .__                     .___
_/ ____\|__|___  ___  ____    __| _/
\   __\ |  |\  \/  /_/ __ \  / __ | 
 |  |   |  | >    < \  ___/ / /_/ | 
 |__|   |__|/__/\_ \ \___  >\____ | 
                  \/     \/      \/ 
```

https://docs.npmjs.com/enterprise/using-it#requiring

**Comment by olizilla** [comment]
:+1::sparkles: 
I fully approve of this asciification.
