### ISSUE TITLE
The "See Also" section should contain links instead of list items

### ISSUE THREAD

**Issue by cepo88** [npm/docs.npmjs.com#123]
The [See Also](https://docs.npmjs.com/misc/developers#see-also) section contains only list items like
* npm-faq(7)
* npm(1)

It will be more usefull if there was links pointing to to corresponding page.
Example:
* [npm-faq(7)](https://docs.npmjs.com/misc/faq)
* [npm(1)](https://docs.npmjs.com/getting-started/what-is-npm)

**Comment by KenanY** [comment]
https://github.com/npm/docs.npmjs.com/issues/106
