### ISSUE TITLE
Can .npmignore files contain comments?

### ISSUE THREAD

**Issue by zeke** [npm/docs.npmjs.com#93]
Do the [rules of gitignore](http://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#Ignoring-Files) apply to `.npmignore`? Specifically:

> Blank lines or lines starting with # are ignored.

If so, I'll add a note about it on this doc:
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

// @isaacs

**Comment by zeke** [comment]
Docs landed in https://github.com/npm/npm/pull/7044 -- yay!

**Comment by ORESoftware** [comment]
and for ease of reference, how can we add comments in .gitignore / .npmignore?
